name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Get latest smake
      uses: lukka/get-cmake@latest
    
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: ${{ github.workspace }}/external/vcpkg
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Run CMake+vcpkg+Ninja+CTest to build packages and generate/build/test the code.
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'ninja-multiconfiguration-vcpkg'
        buildPreset: 'ninja-multiconfiguration-vcpkg'
        buildPresetAdditionalArgs: "[`--config`, `${{env.BUILD_TYPE}}`]"
        testPreset: 'ninja-multiconfiguration-vcpkg'
        testPresetAdditionalArgs: "[`--config`, `${{env.BUILD_TYPE}}`]"

